name: unit-test

on:
  workflow_run:
    workflows: ["Notify unit test"]
    types:
      - completed

jobs:
  post-test-success:
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-workflow_run-status@v1
      - uses: actions/checkout@v2
      - run: exit 0

  post-test-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-workflow_run-status@v1
      - uses: actions/checkout@v2
      - run: exit 1

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cached dependencies
        uses: actions/cache@v2
        id: cached-dependencies
        with:
          path: ./vendor
          # the key will change if composer.lock changes
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/composer.lock') }}

      - name: install dependencies
        if: steps.cached-dependencies.outputs.cache-hit != 'true'
        uses: php-actions/composer@v5

      - name: run tests
        run: composer run test
